# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  push:
    paths:
      - '.github/workflows/**'
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          
          debug: yes
          user: ROMVoid95
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_timezone: America/Chicago
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: java
          plugin_code_lines: 18
          plugin_code_load: 1000
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 2
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_ignored: CSS, HTML, Go
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: repositories
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_traffic: yes
          repositories_skipped: ROMVoid95/TestGradleProject, ROMVoid95/TestRepo
          
