name: Update

on:
  schedule: [{cron: "0/30 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: ROMVoid95/metrics@master
      with:
          token: ${{ secrets.TOKEN }}
          
          # Options
          user: ROMVoid95
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.community, base.activity, base.metadata
          config_timezone: America/Chicago
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_aliases: javascript:js 
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: shell, batch, html, python, makefile
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_traffic: yes
          repositories_skipped: TestRepo, RandomShit
